Arm simulation
CPRT/cprt_rover_24 pull request #5
Opened 2024-11-30 18:17 UTC by MaybeWilli

2024-11-30 18:32 UTC, ChrisRusu1 requested changes
Keep the Phoenix humble

2024-11-30 18:32 UTC, ChrisRusu1 commented on src/arm_interface/arm_interface/joystickArmController.py
Use the new joystickArmController from 2023Rover main branch, it has GPIO imports around checking the environment, so it doesent need to be commented out

2024-11-30 18:32 UTC, ChrisRusu1 commented on src/arm_interface/launch/armjustjoystick.launch.py
This doesent actually call joy or the joystick arm controller. I think I fixed this in the main of 2023

2024-11-30 18:32 UTC, ChrisRusu1 commented on src/arm_interface/launch/keyboard.launch.py
Ik you said youre probably not going to use the keyboard much, but you shouldnt need the breakout node from drive in this with just the keyboard

2024-11-30 19:29 UTC, ConnorNeed requested changes
Looks good. Just some nitpicky stuff.

2024-11-30 19:29 UTC, ConnorNeed commented on src/keyboard_publisher/src/keyboard_publisher.cpp
> +    for (unsigned long int i = 0; i < poseCmd.goal_angles.size(); i++)
`for (const auto& angle : poseCmd.goal_angles) 
{
  RCLCPP_INFO(this->get_logger(), std::to_string(angle.c_str());}`

2024-11-30 19:29 UTC, ConnorNeed commented on src/keyboard_publisher/src/keyboard_publisher.cpp
> +    std::cin>>d;
`for (size_t=0;  i<6; ++i)
{
    std::cin>>d;
    poseCmd.goal_angles[i] = d/360.0 * 2*3.14159;
}`

2024-11-30 19:29 UTC, ConnorNeed commented on src/keyboard_publisher/src/keyboard_publisher.cpp
> +	poseCmd.current_pose = current_pose;
Indent

2024-11-30 19:29 UTC, ConnorNeed commented on src/keyboard_publisher/package.xml
> +  <depend>moveit_ros_planning_interface</depend>
I think you missed tf2_geometry_msgs, tf2 plus maybe a few others

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
A lot of commented out code. Can any of it be deleted?

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
> +	{
Indent issues

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
> +  //RCLCPP_INFO(this->get_logger(), *(this->get_clock()->now()).to_msg().data.c_str());
remove

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
> +	RCLCPP_INFO(this->get_logger(), "Current pose: %f %f %f %f %f %f %f",
Indent

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
A ton of indent issues on this page

2024-11-30 19:29 UTC, ConnorNeed commented on src/moveit_controller/src/moveit_controller.cpp
> +		//msg.position.y += 0.2;
Remove

2025-01-07 21:43 UTC, ConnorNeed reviewed
Much better!

There is still a bunch of commented out code which is usually frowned upon. If the commented out code will be used at some point within the next month then I am okay with leaving it in. If it's more of a hoarding situation where you don't want to get rid of it "just in case" then we should remove it. Commented out code doesn't get maintained well and adds clutter and confusion. All commented out code should have a seperate comment explaining why it is commented out and when it should be added back in.

Please run the black formatter to pass the CI-CD pipeline

Once Jayden removes the SRDF stuff (and moves it to his own branch) I will approve it.

2025-01-07 21:43 UTC, ConnorNeed commented on src/hardware/src/rover_arm.cpp
This is a really well written file. Good job!

2025-01-11 22:13 UTC, ConnorNeed commented
Please stop adding to this PR. Good PRs are supposed to be relatively small with a singular focus. We can't approve a PR if you are constantly changing it. Please create a new branch for new features.

2025-01-13 15:01 UTC, ConnorNeed commented
Closing this PR for now. On Wednsday Will, Jayden and I will set up the PRs appropriately.

2025-01-13 15:01 UTC, closed without merging