Servo controllers
CPRT/cprt_rover_24 pull request #7
Opened 2024-12-04 16:18 UTC by TheWalrus368

USB Control Working, i2c to be tested on Jetson.

2024-12-05 21:05 UTC, ConnorNeed requested changes
A few suggestions to make it follow ROS2 guidelines a little better.

2024-12-05 21:05 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/servo_client.py
> +        response = Servo_Client.send_request(self, servo1.port, servo1.pos)
```suggestion
        response = Servo_Client.send_request(port=0, pos=2432)
```
Pretty sure this will do what we need

2024-12-05 21:05 UTC, ConnorNeed commented on src/servo_pkg/setup.py
> +        ("share/" + package_name, ["package.xml"]),
Create a launch folder and add it here

2024-12-09 22:14 UTC, TheWalrus368 commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        self.servo = maestro.Controller()
Little confused what you mean by this sorry.

2024-12-31 21:39 UTC, ConnorNeed commented
Status on this PR?

2025-01-03 03:17 UTC, TheWalrus368 commented
Will be updated soon, apologies for the delay.

2025-01-07 03:31 UTC, ConnorNeed requested changes
Getting closer. Think of writing ros nodes like writing libraries: abstract away as much unnecessary headaches as you can from the user and allow the user to configure everything that can change. 

The USB controller library is a pain not being in degrees. Maybe we will just stick to the I2C one. I am tagging Chris and Mat for their opinions as well

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/README.md
> +    pip3 install adafruit-circuitpython-lis3dh
add to first time install script

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/README.md
> +   git clone https://github.com/TheWalrus368/Servo_Controllers.git
Use this repo's url

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/launch/servo_launch.launch.py
We should not launch both servo nodes in the same launch file

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        self.servo = maestro.Controller()
The default is /dev/ttyACM0. However that only works if it is the first usb serial device plugged in. We need to allow for custom paths. The constructor of Controller takes in the path that you want to use. Here is the documentation for ros2 parameters in python https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Using-Parameters-In-A-Class-Python.html

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        self.min = 512
If these change based on the type of servos used we must allow for them to be configured via parameters and be independent for each port. We can not guarentee that all the ports will have the same type of controller

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/i2c_Servo.py
> +        self.MAXROM = 180  # max range of motion of the servo, assuming 180 for now
Should be a parameter and customizable to each servo

2025-01-07 03:31 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
I didn't realize that the library was time based not degree based. Handle the conversion in this node so clients don't have to know this in depth information about the hardware.

2025-01-09 17:15 UTC, ChrisRusu1 commented
The magic numbers for the min and max need to be in a parameter as Connor said, along all the other numbers like that. Seems like for the usb it is easy enough to pass in those values to initialize to the correct one. My main question is about the implementation of the service request for determining the position of the servo. From my understanding the servos dont provide feedback to the controller. So if you go from 0-90 and ask what the position is during travel it will return 90 despite being at 45 for example. This is fine for checking what the last set position is but the service should always be returning the moment it commands the servo correct?

For the i2c one maybe I dont understand the backing library, but shouldn't it need some sort of device id to send the i2c commands to the correct device?

2025-01-09 17:18 UTC, ChrisRusu1 commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        self.servo = maestro.Controller()
the controller init uses ACM0 by default, you should be able to pass in the value from the parameter when initializing like the link Connor sent. Should be something like maestro.Controller(parameter)
def __init__(self, ttyStr="/dev/ttyACM0", device=0x0C):
^thats from the maestro file where it inits at ACM0 by default

2025-01-13 15:24 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/servo_client.py
> +    def servo_request(self, con_type: str, req_port, req_pos) -> None:
con_type is never used

2025-01-13 15:24 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/servo_client.py
> +        self.servo_request(self, 0, random_pos_usb, 0, 180)
The order of this seems wrong based on above definition
When using self.funcName(), self is passed in automatically

2025-01-16 03:47 UTC, noodlekid commented
Please format before merge. 🙏

2025-01-16 17:09 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        self.max = 6000  # 180 Degrees
I think 359 or 360 degrees being the default would make more sense

2025-01-16 17:09 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +                self.min = 3000
A bunch of magic numbers here still

2025-01-16 17:09 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/i2c_Servo.py
> +        self.MAXROM = 180  # max range of motion of the servo, default 180
All upper case represents a constant value. This is not constant. Also I think 360 would be a better default max.

2025-01-16 17:09 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/i2c_Servo.py
> +        self.servo_list = self.instantiate_servos()
Where is this function?

2025-01-16 17:09 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/servo_client.py
> +        self.req.port = port
This does not need to be a member of the class. Instaniate a new MoveServoRequest at the beginning of the function and use that. No sense introducing a shared resource unnecessarily.

2025-01-16 20:58 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/i2c_Servo.py
> +        self.MAXROM = 180  # max range of motion of the servo, default 180
Ignore the 360 part. You made a good point that we want the default to be the safer option as not all servos can do 180. The upper case comment still applies

2025-01-18 05:39 UTC, noodlekid requested changes
Looks good, just fix that loop

2025-01-18 05:39 UTC, noodlekid commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +        for i in range(0, 11):  # usb controller has 12 channels
This loops for 0 up to and including 10, if you really have 12 channels you want this range to be range(0,12) 

range generates a interable from start to (stop - 1)

2025-01-25 23:35 UTC, ConnorNeed approved these changes
re-enable configurable USB path, otherwise LGTM. The I2C will be our production one. Give Chris and Mat some time to take a peek.

2025-01-25 23:35 UTC, ConnorNeed commented on src/servo_pkg/servo_pkg/USB_Servo.py
> +            # self.get_parameter("serial_port").get_parameter_value().string_value
uncomment

2025-01-29 19:36 UTC, ChrisRusu1 approved these changes
LGTM

2025-01-29 19:38 UTC, merged